# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='Day',
            new_name='day',
        ),
    ]
