# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170913_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='day_number',
        ),
        migrations.AlterField(
            model_name='character',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=19),
        ),
        migrations.AlterField(
            model_name='character',
            name='danger',
            field=models.IntegerField(default=0),
        ),
    ]
