# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170913_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Day'),
        ),
    ]
