# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170914_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_passed',
            field=models.BooleanField(default=False),
        ),
    ]
